@startuml
actor Main
participant R as Rectangle
participant C as Circle

Main ->> R : draw()
R -->> Main : "Rysuję prostokąt o bokach w x h"
Main ->> R : area()
R -->> Main : width * height

Main ->> C : draw()
C -->> Main : "Rysuję kształt: Koło" \(implementacja z Shape\)
Main ->> C : area()
C -->> Main : PI * r^2
@enduml
